version: '3'

services:
  web:
    image: kalyankumar13/python_app_ica3
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
