version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sys
    volumes:
      - vol:/var/lib/mysql
    ports:
      - "3308:3306"
    # networks:
    #   - app

  project-app:
    image: project-app
    container_name: project-app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    # networks:
    #   - app

# networks:
#   app:

volumes:
  vol:
