version: '3.8'

services:
  mysql:
    image: mysql
    deploy:
      replicas: 1  # Adjust as needed
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sys
    volumes:
      - vol:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app

  project-app:
    image: kalyankumar13/spring-projectimage:latest
    deploy:
      replicas: 1  # Adjust as needed
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app:

volumes:
  vol:
