apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
