apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'sleep 35']
        #command: ['sh', '-c', 'until nc -z mysql 3306; do echo "Waiting for MySQL service"; sleep 5; done;']
      containers:
      - name: project-app
        image: {{ .Values.projectApp.image }}
        env:
        - name: MYSQL_HOST
          value: {{ include "my-chart.fullname" . }}-mysql
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 8080
       
