apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-project-app
spec:
  type: NodePort
  selector:
    app: project-app
  ports:
    - protocol: TCP
      port: 8009
      targetPort: 8080
