apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tester-read-only-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: tester-service-account
  namespace: default
roleRef:
  kind: Role
  name: tester-read-only
  apiGroup: rbac.authorization.k8s.io
