apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      containers:
      - name: project-app
        image: kalyankumar13/spring-projectimage:latest
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 8080
